version: '4'
services:
  matcher-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: fingerprint-matcher:latest
    volumes:
     - ./.env:/matcher/.env
    ports:
     - "4040:4040"
    deploy:
      restart_policy:
          condition: always
