include:
  - project: 'cledar/kim/signals/common-ci'
    ref: master
    file: '/.gitlab-ci-template.yml'

version:
  extends: .version

black:
  extends: .black

pylint:
  extends: .pylint

mypy:
  extends: .mypy

test:
  extends: .test

sonarcloud-check:
  extends: .sonarcloud-check
