include:
  - project: 'cledar/kim/signals/pipeline/common-ci'
    ref: KSR-370-improve-linting-stage-performance-in-ci-pipeline
    file: '/.gitlab-ci-template.yml'

version:
  extends: .version

black:
  extends: .black

pylint:
  extends: .pylint

mypy:
  extends: .mypy

test:
  extends: .test

sonarcloud-check:
  extends: .sonarcloud-check
