repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: [pylint]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        args: [--strict]
        additional_dependencies: [
            pydantic==2.7.4,
            pytest==8.2.2,
            Faker==26.0.0,
            "fastapi>=0.112.3,<0.113.0",
            "prometheus-client>=0.20.0,<0.21.0",
            "uvicorn>=0.30.6,<0.31.0",
            boto3-stubs==1.34.138,
        ]
