repos:
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        language: system
        entry: poetry run black
        types: [python]


-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: python
        types: [python]
        require_serial: true
        additional_dependencies: [pylint]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        language: system
        entry: poetry run mypy
        types: [python]
        additional_dependencies: [
            pydantic==2.7.4,
        ]
