# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_data.proto
# Protobuf Python Version: 4.25.3
# pylint: skip-file
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x61pp_data.proto\x12\rapp_data_haha"`\n\x0cPeaksBatches\x12*\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x19.app_data_haha.PeaksBatch\x12\x11\n\tsyne_uuid\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t"h\n\nPeaksBatch\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\r\x12\x14\n\x08\x63hannel1\x18\x04 \x03(\rB\x02\x10\x01\x12\x14\n\x08\x63hannel2\x18\x05 \x03(\rB\x02\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "app_data_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PEAKSBATCH"].fields_by_name["channel1"]._options = None
    _globals["_PEAKSBATCH"].fields_by_name["channel1"]._serialized_options = b"\020\001"
    _globals["_PEAKSBATCH"].fields_by_name["channel2"]._options = None
    _globals["_PEAKSBATCH"].fields_by_name["channel2"]._serialized_options = b"\020\001"
    _globals["_PEAKSBATCHES"]._serialized_start = 33
    _globals["_PEAKSBATCHES"]._serialized_end = 129
    _globals["_PEAKSBATCH"]._serialized_start = 131
    _globals["_PEAKSBATCH"]._serialized_end = 235
# @@protoc_insertion_point(module_scope)
