# pylint: skip-file
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app_data.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="app_data.proto",
    package="app_data_haha",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0e\x61pp_data.proto\x12\rapp_data_haha"`\n\x0cPeaksBatches\x12*\n\x07\x62\x61tches\x18\x01 \x03(\x0b\x32\x19.app_data_haha.PeaksBatch\x12\x11\n\tsyne_uuid\x18\x02 \x01(\t\x12\x11\n\tclient_id\x18\x03 \x01(\t"h\n\nPeaksBatch\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\r\n\x05start\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\r\x12\x14\n\x08\x63hannel1\x18\x04 \x03(\rB\x02\x10\x01\x12\x14\n\x08\x63hannel2\x18\x05 \x03(\rB\x02\x10\x01\x62\x06proto3'
    ),
)


_PEAKSBATCHES = _descriptor.Descriptor(
    name="PeaksBatches",
    full_name="app_data_haha.PeaksBatches",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="batches",
            full_name="app_data_haha.PeaksBatches.batches",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="syne_uuid",
            full_name="app_data_haha.PeaksBatches.syne_uuid",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="client_id",
            full_name="app_data_haha.PeaksBatches.client_id",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=33,
    serialized_end=129,
)


_PEAKSBATCH = _descriptor.Descriptor(
    name="PeaksBatch",
    full_name="app_data_haha.PeaksBatch",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="version",
            full_name="app_data_haha.PeaksBatch.version",
            index=0,
            number=1,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="start",
            full_name="app_data_haha.PeaksBatch.start",
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="length",
            full_name="app_data_haha.PeaksBatch.length",
            index=2,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="channel1",
            full_name="app_data_haha.PeaksBatch.channel1",
            index=3,
            number=4,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=_b("\020\001"),
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="channel2",
            full_name="app_data_haha.PeaksBatch.channel2",
            index=4,
            number=5,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=_b("\020\001"),
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=131,
    serialized_end=235,
)

_PEAKSBATCHES.fields_by_name["batches"].message_type = _PEAKSBATCH
DESCRIPTOR.message_types_by_name["PeaksBatches"] = _PEAKSBATCHES
DESCRIPTOR.message_types_by_name["PeaksBatch"] = _PEAKSBATCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PeaksBatches = _reflection.GeneratedProtocolMessageType(
    "PeaksBatches",
    (_message.Message,),
    dict(
        DESCRIPTOR=_PEAKSBATCHES,
        __module__="app_data_pb2",
        # @@protoc_insertion_point(class_scope:app_data_haha.PeaksBatches)
    ),
)
_sym_db.RegisterMessage(PeaksBatches)

PeaksBatch = _reflection.GeneratedProtocolMessageType(
    "PeaksBatch",
    (_message.Message,),
    dict(
        DESCRIPTOR=_PEAKSBATCH,
        __module__="app_data_pb2",
        # @@protoc_insertion_point(class_scope:app_data_haha.PeaksBatch)
    ),
)
_sym_db.RegisterMessage(PeaksBatch)


_PEAKSBATCH.fields_by_name["channel1"]._options = None
_PEAKSBATCH.fields_by_name["channel2"]._options = None
# @@protoc_insertion_point(module_scope)
