#ifndef COMMON_H
#define COMMON_H

// NOLINTBEGIN

typedef int16_t sample_t;
typedef float spec_t;

#define SAMPLE_HZ 44100
#define CUTOFF_FREQ 10000

#define MAGIC_5000 5000
#define MAGIC_100 100
#define MAGIC_10 10
#define MAGIC_0_5 0.5
#define MAGIC_2_ 2.
#define PROBABLY_SFRAME_TIME_OFFSET 0.0928
#define MAGIC_THRESHOLD 0.01F

// SFRAME - spectrogram frame
#define SFRAME_IN_SIZE 8192
#define READ_BUFFER_MULT 10
#define SFRAME_READ_SIZE (SFRAME_IN_SIZE * READ_BUFFER_MULT)
#define SFRAME_OUT_SIZE (SFRAME_IN_SIZE / 2 + 1)

// PFRAME - peaks frame
// dy < MASK_RX && dx < MASK_RY
#define MASK_RX 3
#define MASK_RY 4
#define PFRAME_WIDTH MASK_RX
#define PFRAME_CELL_HEIGHT MASK_RY
#define PFRAME_CELLS \
  (SFRAME_OUT_SIZE * (CUTOFF_FREQ * 2) / SAMPLE_HZ / PFRAME_CELL_HEIGHT)
#define PFRAME_HEIGHT (PFRAME_CELLS * PFRAME_CELL_HEIGHT)
#define PFRAME_MIN_VAL 50000

// NOLINTEND
#endif  // COMMON_H