include:
  - path: ../../services/reference-buffering-server/docker-compose.yml
    env_file:
      - ../../services/reference-buffering-server/.env.example

services:
  audio-fingerprinting:
    image: audio-fingerprinting
    build:
      context: .
    command: --kafka-address redpanda-0:9092 /resources/radio/audio.wav --offset 0 --channel 10 --station-id kim --start-ts 0
    networks:
      - redpanda_network
    depends_on:
      - redpanda-0
    volumes:
      - ${PWD}/resources/radio/audio.wav:/resources/radio/audio.wav
  e2e-tests:
    image: audio-fingerprinting-e2e
    build:
      context: .
      target: build
      cache_from:
        - audio-fingerprinting
    entrypoint: [""]
    command: meson compile e2e_test -C build
    networks:
      - redpanda_network
    depends_on:
      - redpanda-0
    profiles:
      - donotstart